# services:
#   - type: worker                  # worker — це фоновий процес
#     name: tg-monitoring           # Назва сервісу
#     env: python                   # Середовище виконання Python
#     plan: free                    # План використання, наприклад, безкоштовний план
#     buildCommand: pip install -r requirements.txt  # Команда для встановлення залежностей
#     startCommand: python main.py  # Команда для запуску скрипту


services:
  - type: web
    name: tg-monitoring
    env: python
    runtime: python3.11
    branch: main
    buildCommand: ""
    startCommand: python main.py
    autoDeploy: true
    plan: free

